2022-11-03 00:13:27,598 - __init__ - initialize_logger - line:23 - INFO - Logging Initialized
2022-11-03 00:13:27,598 - __init__ - initialize_logger - line:24 - DEBUG - Logging debug
2022-11-03 00:13:27,598 - __init__ - initialize_logger - line:25 - WARNING - Logging warning
2022-11-03 00:13:27,598 - __init__ - initialize_logger - line:26 - ERROR - Error here
2022-11-03 00:13:27,598 - __init__ - initialize_logger - line:27 - ERROR - Exception here
NoneType: None
2022-11-03 00:13:27,843 - selector_events - __init__ - line:54 - DEBUG - Using selector: KqueueSelector
2022-11-03 00:13:27,851 - selector_events - __init__ - line:54 - DEBUG - Using selector: KqueueSelector
2022-11-03 00:13:29,651 - selector_events - __init__ - line:54 - DEBUG - Using selector: KqueueSelector
2022-11-03 00:13:29,653 - selector_events - __init__ - line:54 - DEBUG - Using selector: KqueueSelector
2022-11-03 00:13:30,422 - __init__ - wrapping_logic - line:34 - INFO - Request 8cfc52f90519431e9a21ff74d742da4c entering  function get_password_hash
2022-11-03 00:13:30,423 - bcrypt - _load_backend_mixin - line:625 - DEBUG - detected 'bcrypt' backend, version '4.0.1'
2022-11-03 00:13:30,424 - bcrypt - _finalize_backend_mixin - line:406 - DEBUG - 'bcrypt' backend lacks $2$ support, enabling workaround
2022-11-03 00:13:31,230 - __init__ - wrapping_logic - line:39 - INFO - Request 8cfc52f90519431e9a21ff74d742da4c exiting function get_password_hash total time 0.807607889175415
2022-11-03 00:13:31,525 - __init__ - create_response - line:57 - INFO - Creating response with data:{'message': 'User created!', 'item': {'email': 'test@gmail.com', 'id': 1, 'username': 'Test_user', 'updated_at': '2022-11-03 00:13:26', 'created_at': '2022-11-03 00:13:26'}, 'status': 200}
2022-11-03 00:13:31,528 - _client - _send_single_request - line:1728 - DEBUG - HTTP Request: POST http://test/users/sign-up "HTTP/1.1 200 OK"
2022-11-03 00:13:31,546 - __init__ - wrapping_logic - line:34 - INFO - Request 92df51a4c3194ec3a30273cfb910ffc1 entering  function request_body_extraction
2022-11-03 00:13:31,547 - __init__ - wrapping_logic - line:39 - INFO - Request 92df51a4c3194ec3a30273cfb910ffc1 exiting function request_body_extraction total time 0.00045680999755859375
2022-11-03 00:13:31,594 - __init__ - wrapping_logic - line:34 - INFO - Request 92df51a4c3194ec3a30273cfb910ffc1 entering  function verify_password
2022-11-03 00:13:32,093 - __init__ - wrapping_logic - line:39 - INFO - Request 92df51a4c3194ec3a30273cfb910ffc1 exiting function verify_password total time 0.49883532524108887
2022-11-03 00:13:32,093 - __init__ - wrapping_logic - line:34 - INFO - Request 92df51a4c3194ec3a30273cfb910ffc1 entering  function create_access_token
2022-11-03 00:13:32,095 - __init__ - wrapping_logic - line:39 - INFO - Request 92df51a4c3194ec3a30273cfb910ffc1 exiting function create_access_token total time 0.0017428398132324219
2022-11-03 00:13:32,095 - __init__ - create_response - line:57 - INFO - Creating response with data:{'message': 'User logged in!', 'item': {'token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3RfdXNlciIsImVtYWlsIjoidGVzdEBnbWFpbC5jb20iLCJwYXNzd29yZCI6InRlc3QiLCJleHAiOjE2Njc0MzA4MTJ9.ZgLLpXGc03pAHcFAByb5Z4OxogvY5SlnNktOl1mmk1s', 'user': {'email': 'test@gmail.com', 'id': 1, 'username': 'Test_user', 'updated_at': '2022-11-03 00:13:26', 'created_at': '2022-11-03 00:13:26'}}, 'status': 200}
2022-11-03 00:13:32,096 - _client - _send_single_request - line:1728 - DEBUG - HTTP Request: POST http://test/users/login "HTTP/1.1 200 OK"
2022-11-03 00:13:32,097 - __init__ - create_response - line:57 - INFO - Creating response with data:{'message': 'Password is not present', 'item': No2022-11-03 00:13:32,101 - __init__ - wrapping_logic - line:39 - INFO - Request 54434f2c78c3429d95fcfe2c2870402c exiting function authenthicate_user total time 0.0075550079345703125
2022-11-03 00:13:32,101 - __init__ - create_response - line:57 - INFO - Creating response with data:{'message': 'Do not send params for this endpoint!', 'item': None, 'status': 400}
2022-11-03 00:13:32,102 - _client - _send_single_request - line:1728 - DEBUG - HTTP Request: POST http://test/users/create_users/100 "HTTP/1.1 200 OK"
2022-11-03 00:13:32,103 - __init__ - wrapping_logic - line:34 - INFO - Request 2c3808445a4f4b96b94999796dc09832 entering  function authenthicate_user
2022-11-03 00:13:32,121 - __init__ - wrapping_logic - line:39 - INFO - Request 2c3808445a4f4b96b94999796dc09832 exiting function authenthicate_user total time 0.01743793487548828
2022-11-03 00:13:32,121 - __init__ - wrapping_logic - line:34 - INFO - Request 2c3808445a4f42022-11-03 00:13:32,562 - __init__ - wrapping_logic - line:39 - INFO - Request 7507dd855fea4fb1abdcd4d0f6f25d91 exiting function get_password_hash total time 0.4586622714996338
2022-11-03 00:13:32,574 - __init__ - create_response - line:57 - INFO - Creating response with data:{'message': 'User created!', 'item': {'email': 'test_alternate@gmail.com', 'id': 2, 'username': 'test_duplicate', 'updated_at': '2022-11-03 00:13:26', 'created_at': '2022-11-03 00:13:26'}, 'status': 200}
2022-11-03 00:13:32,575 - _client - _send_single_request - line:1728 - DEBUG - HTTP Request: POST http://test/users/sign-up "HTTP/1.1 200 OK"
2022-11-03 00:13:32,577 - __init__ - wrapping_logic - line:34 - INFO - Request 4eea56f7f4e04b1ab114072959ec7f23 entering  function get_password_hash
2022-11-03 00:13:33,043 - __init__ - wrapping_logic - line:39 - INFO - Request 4eea56f7f4e04b1ab114072959ec7f23 exiting function get_password_hash total time 0.4668862819671631
2022-11-03 00:13:33,069 - __init__ - create_response - line:57 - INFO - Creating response with data:{'message': '(sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class \'asyncpg.exceptions.UniqueViolationError\'>: duplicate key value violates unique constraint "users_username_key"\nDETAIL:  Key (username)=(test_duplicate) already exists.\n[SQL: INSERT INTO users (created_at, updated_at, username, email, hashed_pass, permissions) VALUES (%s, %s, %s, %s, %s, %s) RETURNING users.id]\n[parameters: (datetime.datetime(2022, 11, 3, 0, 13, 26, 121282), datetime.datetime(2022, 11, 3, 0, 13, 26, 121426), \'test_duplicate\', \'test_alternate@gmail.com\', \'$2b$12$Pib14UcV.H9MCslYunbtUOsUO6Mbwv1CewW0NM0aae0YL5r8fcYAq\', None)]\n(Background on this error at: https://sqlalche.me/e/14/gkpj)', 'item': None, 'status': 400}
2022-11-03 00:13:33,070 - _client - _send_single_request - line:1728 - DEBUG - HTTP Request: POST http://test/users/sign-up "HTTP/1.1 200 OK"
2022-11-03 00:13:33,071 - __init__ - wrapping_logic - line:34 - INFO - Request 6d069c02422a4de1b4d261dd7fb871cd entering  function authenthicate_user
2022-11-03 00:13:33,083 - __init__ - wrapping_logic - line:39 - INFO - Request 6d069c02422a4de1b4d261dd7fb871cd exiting function authenthicate_user total time 0.011095046997070312
2022-11-03 00:13:33,096 - __init__ - create_response - line:57 - INFO - Creating response with data:{'message': 'User fetched!', 'item': {'email': 'test_alternate@gmail.com', 'id': 2, 'username': 'test_duplicate', 'updated_at': '2022-11-03 00:13:26', 'created_at': '2022-11-03 00:13:26'}, 'status': 200}
2022-11-03 00:13:33,099 - _client - _send_single_request - line:1728 - DEBUG - HTTP Request: GET http://test/users/get_user/2 "HTTP/1.1 200 OK"
2022-11-03 00:13:33,100 - __init__ - wrapping_logic - line:34 - INFO - Request 30f407f93630415396c9f86092d75c6f entering  function authenthicate_user
2022-11-03 00:13:33,109 - __init__ - wrapping_logic - line:39 - INFO - Request 30f407f93630415396c9f86092d75c6f exiting function authenthicate_user total time 0.008694887161254883
2022-11-03 00:13:33,125 - __init__ - create_response - line:57 - INFO - Creating response with data:{'message': 'User not found!', 'item': None, 'status': 400}
2022-11-03 00:13:33,127 - _client - _send_single_request - line:1728 - DEBUG - HTTP Request: GET http://test/users/get_user/3 "HTTP/1.1 200 OK"
2022-11-03 00:13:33,129 - __init__ - wrapping_logic - line:34 - INFO - Request 91c4983d71674df2904ef952a0090a16 entering  function authenthicate_user
2022-11-03 00:13:33,130 - __init__ - wrapping_logic - line:43 - ERROR - Exception  91c4983d71674df2904ef952a0090a16 raised in authenthicate_user. exception: Not enough segments
Traceback (most recent call last):
  File "/Users/mika/Desktop/code/myrepos/fast-api-full/venv/lib/python3.10/site-packages/jose/jws.py", line 176, in _load
    signing_input, crypto_segment = jwt.rsplit(b".", 1)
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mika/Desktop/code/myrepos/fast-api-full/venv/lib/python3.10/site-packages/jose/jwt.py", line 142, in decode
    payload = jws.verify(token, key, algorithms, verify=verify_signature)
  File "/Users/mika/Desktop/code/myrepos/fast-api-full/venv/lib/python3.10/site-packages/jose/jws.py", line 70, in verify
    header, p2022-11-03 00:13:33,137 - __init__ - wrapping_logic - line:39 - INFO - Request 704422eb43f044c09817b5fcb5184de6 exiting function authenthicate_user total time 0.012971162796020508
2022-11-03 00:13:33,154 - __init__ - create_response - line:57 - INFO - Creating response with data:{'message': '(sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class \'asyncpg.exceptions.UniqueViolationError\'>: duplicate key value violates unique constraint "users_username_key"\nDETAIL:  Key (username)=(user_test) already exists.\n[SQL: INSERT INTO users (created_at, updated_at, username, email, hashed_pass, permissions) VALUES (%s, %s, %s, %s, %s, %s) RETURNING users.id]\n[parameters: (datetime.datetime(2022, 11, 3, 0, 13, 26, 221031), datetime.datetime(2022, 11, 3, 0, 13, 26, 221202), \'user_test\', \'email@gmail.com\', \'hashed pass\', None)]\n(Background on this error at: https://sqlalche.me/e/14/gkpj)', 'item': None, 'status': 400}
2022-11-03 00:13:33,156 - _client - _send_single_request - line:1728 - DEBUG - HTTP Request: POST http://test/users/create_user "HTTP/1.1 200 OK"
2022-11-03 00:13:33,157 - __init__ - wrapping_logic - line:34 - INFO - Request a81754c6c1324588b5abab5dde252b93 entering  function authenthicate_user
2022-11-03 00:13:33,167 - __init__ - wrapping_logic - line:39 - INFO - Request a81754c6c1324588b5abab5dde252b93 exiting function authenthicate_user total time 0.010050773620605469
2022-11-03 00:13:33,174 - __init__ - create_response - line:57 - INFO - Creating response with data:{'message': '(sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <clas2022-11-03 00:13:33,307 - selector_events - __init__ - line:54 - DEBUG - Using selector: KqueueSelector
raint\nDETAIL:  Failing row contains (6, 2022-11-03 00:13:26.221031, 2022-11-03 00:13:26.221202, null, null, null, null).\n[SQL: INSERT INTO users (created_at, updated_at, username, email, hashed_pass, permissions) VALUES (%s, %s, %s, %s, %s, %s) RETURNING users.id]\n[parameters: (datetime.datetime(2022, 11, 3, 0, 13, 26, 221031), datetime.datetime(2022, 11, 3, 0, 13, 26, 221202022-11-03 00:13:33,323 - selector_events - __init__ - line:54 - DEBUG - Using selector: KqueueSelector
e, 'status': 400}
2022-11-03 00:13:33,175 - _client - _send_single_request - line:1728 - DEBUG - HTTP Request: POST http://test/users/create_user "HTTP/1.1 200 OK"
2022-11-03 00:13:33,350 - selector_events - __init__ - line:54 - DEBUG - Using selector: KqueueSelector
est_body_extraction
2022-11-03 00:13:32,925 - __init__ - wrapping_logic - line:39 - INFO - Request 87646b5115814628829d08cd7749975f exiting function request_body_extraction total time 0.00012493133544921875
2022-11-03 00:13:32,925 - __init__ - create_response - line:57 - INFO - Creating response with data:{'message': 'Email is required', 'item': None, 'status': 400}
2022-11-03 00:13:32,926 - _client - _send_single_request - line:1728 - DEBUG - HTTP Request: POST http://test/users/login "HTTP/1.1 200 OK"
2022-11-03 00:13:32,926 - __init__ - wrapping_logic - line:34 - INFO - Request 9d0151657199495fafcde036e91fbf11 entering  function request_body_extraction
2022-11-03 00:13:32,926 - __init__ - wrapping_logic - line:39 - INFO - Request 9d0151657199495fafcde036e91fbf11 exiting function request_body_extraction total time 8.916854858398438e-05
2022-11-03 00:13:32,926 - __init__ - create_response - line:57 - INFO - Creating response with data:{'message': 'Password is required', 'item': None, 'status': 400}
2022-11-03 00:13:32,927 - _client - _send_single_request - line:1728 - DEBUG - HTTP Request: POST http://test/users/login "HTTP/1.1 200 OK"
2022-11-03 00:13:32,928 - __init__ - wrapping_logic - line:34 - INFO - Request 8017f90233d047aa9bb559a42bf2623b entering  function request_body_extraction
2022-11-03 00:13:32,928 - __init__ - wrapping_logic - line:39 - INFO - Request 8017f90233d047aa9bb559a42bf2623b exiting function request_body_extraction total time 8.797645568847656e-05
2022-11-03 00:13:32,934 - __init__ - create_response - line:57 - INFO - Creating response with data:{'message': 'No user with such email found', 'item': None, 'status': 400}
2022-11-03 00:13:32,935 - _client - _send_single_request - line:1728 - DEBUG - HTTP Request: POST http://test/users/login "HTTP/1.1 200 OK"
2022-11-03 00:13:32,935 - __init__ - wrapping_logic - line:34 - INFO - Request 4f8641fd7b8e41f4bee70da1c83bd0bb entering  function request_body_extraction
2022-11-03 00:13:32,935 - __init__ - wrapping_logic - line:39 - INFO - Request 4f8641fd7b8e41f4bee70da1c83bd0bb exiting function request_body_extraction total time 9.989738464355469e-05
2022-11-03 00:13:32,941 - __init__ - wrapping_logic - line:34 - INFO - Request 4f8641fd7b8e41f4bee70da1c83bd0bb entering  function verify_password
2022-11-03 00:13:33,458 - __init__ - wrapping_logic - line:39 - INFO - Request 4f8641fd7b8e41f4bee70da1c83bd0bb exiting function verify_password total time 0.5169799327850342
2022-11-03 00:13:33,458 - __init__ - create_response - line:57 - INFO - Creating response with data:{'message': 'Incorrect password!', 'item': None, 'status': 400}
2022-11-03 00:13:33,459 - _client - _send_single_request - line:1728 - DEBUG - HTTP Request: POST http://test/users/login "HTTP/1.1 200 OK"
2022-11-03 00:13:33,602 - selector_events - __init__ - line:54 - DEBUG - Using selector: KqueueSelector
